### ISSUE TITLE
Show problem

### ISSUE THREAD

**Issue by jorgefandinno** [bramucas/xclingo2#1]
Running "xclingo problems/show.lp --auto-tracing all" with the following program produces no explanation. Removing the show produces the expected explanations.

a(1).
b(X) :- a(X).

#show b/1.
%!show_trace b(X).

**Comment by bramucas** [comment]
Fixed.

#show statements are now ignored when obtaining the models of the original program.

Before the fix, only shown atoms were collected from the original program. Therefore (for the previous example) xclingo thinks a(1) is not true so there isn't any valid explanation for b(1).

Please update xclingo via pip (python3 -m pip install --upgrade xclingo)
